# Generated by Django 5.0.1 on 2024-03-09 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment_codes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollmentcode',
            old_name='code',
            new_name='EnrollCode',
        ),
    ]
