# Generated by Django 5.0.1 on 2024-03-09 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0015_remove_course_enroll_codes_course_enroll_code'),
        ('enrollment_codes', '0006_alter_enrollmentcode_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollmentcode',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_codes', to='course.course'),
        ),
    ]
