# Generated by Django 5.0.1 on 2024-03-09 23:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0016_remove_course_enroll_code_course_enroll_codes'),
        ('enrollment_codes', '0007_alter_enrollmentcode_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollmentcode',
            name='EnrollCode',
            field=models.CharField(blank=True, max_length=5, null=True, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9]*$', 'Only alphanumeric characters are allowed.'), django.core.validators.MinLengthValidator(5), django.core.validators.MaxLengthValidator(5)]),
        ),
        migrations.AlterField(
            model_name='enrollmentcode',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course'),
        ),
    ]
