# Generated by Django 5.0.3 on 2024-03-10 02:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment_codes', '0009_alter_enrollmentcode_enrollcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollmentcode',
            name='EnrollCode',
            field=models.CharField(blank=True, max_length=5, null=True, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9]*$', 'Only alphanumeric characters are allowed.'), django.core.validators.MaxLengthValidator(5)]),
        ),
    ]
