# Generated by Django 4.2.6 on 2023-11-07 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_rename_courses_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='number',
            field=models.PositiveSmallIntegerField(default=1000),
            preserve_default=False,
        ),
    ]
