# Generated by Django 5.0.1 on 2024-02-15 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_course_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='combined_name',
            field=models.CharField(default='<django.db.models.fields.CharField><django.db.models.fields.PositiveSmallIntegerField>', max_length=8, unique=True),
        ),
    ]
