# Generated by Django 5.0.1 on 2024-02-15 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0012_remove_course_combined_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='enrollCode',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
