# Generated by Django 5.0.1 on 2024-03-09 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0013_course_enrollcode'),
        ('enrollment_codes', '0003_alter_enrollmentcode_enrollcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='enrollCode',
        ),
        migrations.AddField(
            model_name='course',
            name='enroll_codes',
            field=models.ManyToManyField(blank=True, related_name='courses', to='enrollment_codes.enrollmentcode'),
        ),
    ]
