# Generated by Django 5.0.1 on 2024-03-09 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0014_remove_course_enrollcode_course_enroll_codes'),
        ('enrollment_codes', '0006_alter_enrollmentcode_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='enroll_codes',
        ),
        migrations.AddField(
            model_name='course',
            name='enroll_code',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_enroll_code', to='enrollment_codes.enrollmentcode'),
        ),
    ]
