# Generated by Django 5.0.1 on 2024-03-09 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0015_remove_course_enroll_codes_course_enroll_code'),
        ('enrollment_codes', '0007_alter_enrollmentcode_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='enroll_code',
        ),
        migrations.AddField(
            model_name='course',
            name='enroll_codes',
            field=models.ManyToManyField(blank=True, related_name='courses', to='enrollment_codes.enrollmentcode'),
        ),
    ]
