# Generated by Django 5.0.1 on 2024-03-09 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0016_remove_course_enroll_code_course_enroll_codes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='enroll_codes',
            new_name='EnrollCode',
        ),
    ]
