# Generated by Django 5.0.3 on 2024-03-10 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0017_rename_enroll_codes_course_enrollcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='EnrollCode',
        ),
    ]
