# Generated by Django 5.0.3 on 2024-03-10 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_thumbnail_img'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thumbnail',
            options={'ordering': ('-id',)},
        ),
    ]
