# Generated by Django 5.0.4 on 2024-04-24 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_thumbnail_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Thumbnail',
        ),
    ]
