# Generated by Django 5.0.4 on 2024-04-24 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_remove_pdfdocument_pdf_file_pdffile'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdffile',
            name='img',
            field=models.FileField(default='placeholderPreview.jpg', upload_to='pic/%y/'),
        ),
    ]
