# Generated by Django 5.0.1 on 2024-02-15 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userinformation',
            options={'verbose_name': 'User Information', 'verbose_name_plural': 'User Information'},
        ),
    ]
