# Generated by Django 5.0.1 on 2024-02-15 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0004_alter_userinformation_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinformation',
            name='user',
        ),
    ]
