# Generated by Django 5.0.1 on 2024-02-15 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0007_alter_userinformation_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinformation',
            name='name',
            field=models.CharField(default=models.CharField(max_length=20), max_length=20),
        ),
    ]
